image: node:10.15.3

stages:
  - install_dependencies
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  script:
    - npm i
  only:
    changes:
      - package.json
      

build_job:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

unit_test:
  stage: test
  script:
    - npm test

code_quality:
  stage: test
  script:
    - npm test

performance:
  stage: test
  script:
    - npm test

deploy as review app:
  image: rambabusaravanan/firebase
  stage: deploy
  only:
    - develop
    - master
  environment:
    name: review
    url: https://admin-waza-membership.web.app
  script:
    - firebase use waza-membership --token $FIREBASE_TOKEN
    - firebase target:apply hosting admin admin-waza-membership
    - firebase deploy --only hosting -m "Commit $CI_COMMIT_TITLE Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN